# Generated by Django 5.0.1 on 2024-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0002_thread_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="updated",
        ),
        migrations.AddField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
