# Generated by Django 5.0.1 on 2024-03-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0003_remove_thread_updated_message_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-updated"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="updated",
        ),
        migrations.AddField(
            model_name="thread",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
